### ISSUE TITLE
Bug sa bazom na develop-u

### ISSUE THREAD

**Issue by anamarojevic** [igen-ftn/igenhub#9]

**Comment by kimnovak** [comment]
fali initial migration imali smo sličan problem na zekinoj grani ali je tad rešilo samo za igenapp, sad je meni proradilo nakon:
docker-compose run web python manage.py makemigrations igenapp
docker-compose run web python manage.py migrate igenapp
docker-compose run web python manage.py makemigrations admin
docker-compose run web python manage.py migrate admin
docker-compose run web python manage.py makemigrations auth
docker-compose run web python manage.py migrate auth
docker-compose run web python manage.py makemigrations contenttypes
docker-compose run web python manage.py migrate contenttypes
docker-compose run web python manage.py makemigrations sessions
docker-compose run web python manage.py migrate sessions
